### ISSUE TITLE
无法选中block

### ISSUE THREAD

**Issue by PayneSnow** [yoyooyooo/roam-enhance#2]
您好，你的这个插件很棒，然后在使用一段时间后，发现和另外一个主题冲突。
我安装了[Styled Roam](https://github.com/JimmyLv/styled-roam)这个主题，还有 roam42，随后才安装了Quick start(zh-CN)。使用一段时间后，刚开始正常。后来发现无法同时选中多个block。关闭Quick start后，就恢复正常了。不知道什么原因。

**Comment by yoyooyooo** [comment]
是拖拽选用多个 block 变成蓝色背景？我一直用没遇到会这样过，我没装过Styled Roam不是很清楚会有什么化学反应，，理论上不会的，能不能录个视频

**Comment by PayneSnow** [comment]
昨天晚上一直有冲突。
刚才重新启用，发现暂时不冲突了。下次遇到我来录屏幕。
我只会copy嵌入代码和点击按钮。这儿给的代码怎么配置呢。也是新建{{[[roam/js]]}}，再嵌入代码吗？
您那边有bilibili等视频吗？
感谢🙏
| |


|
|
***@***.***
|
签名由网易邮箱大师定制


在2021年04月3日 ***@***.***> 写道：

是拖拽选用多个 block 变成蓝色背景？我一直用没遇到会这样过，我没装过Styled Roam不是很清楚会有什么化学反应，，理论上不会的，能不能录个视频

**Comment by yoyooyooo** [comment]
> 昨天晚上一直有冲突。 刚才重新启用，发现暂时不冲突了。下次遇到我来录屏幕。 我只会copy嵌入代码和点击按钮。这儿给的代码怎么配置呢。也是新建{{[[roam/js]]}}，再嵌入代码吗？ 您那边有bilibili等视频吗？ 感谢🙏 | | | | ***@***.*** | 签名由网易邮箱大师定制 在2021年04月3日 ***@***.***> 写道： 是拖拽选用多个 block 变成蓝色背景？我一直用没遇到会这样过，我没装过Styled Roam不是很清楚会有什么化学反应，，理论上不会的，能不能录个视频 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

没看懂。。你是说安装么，安装就是正常的安装方式，和你说的一样任意地方{{[[roam/js]]}}换行 tab 添加 js 代码

**Comment by PayneSnow** [comment]
安装部分有两个代码块。
这个正在运行。
![截屏2021-04-03 15 13 05](https://user-images.githubusercontent.com/51922806/113471476-19433080-948f-11eb-9856-c3089fb26c2e.png)
下面这个roam enhance还需要再建立{{[[roam/js]]}}换行 tab 添加 js 代码吗？
![截屏2021-04-03 15 13 33](https://user-images.githubusercontent.com/51922806/113471480-29f3a680-948f-11eb-89dd-0acbb3c82a94.png)
![截屏2021-04-03 15 17 31](https://user-images.githubusercontent.com/51922806/113471547-b8682800-948f-11eb-9989-af916321c0f1.png)

**Comment by PayneSnow** [comment]
在我上次回复你之后，我重新打开了你的插件。使用几个小时后，刚才出现bug了。如截屏。关闭插件后，又恢复正常了。我安装了chrome的插件roam themes，使用了slightly aesthetic 主题。此外，还安装了 roam42、Styled Roam 主题。主要就是这些。截屏太大了，我发邮件回复。见最新邮件。

**Comment by PayneSnow** [comment]
视频16m，方便的话，给个其他邮箱。我发给您。刚给你发的邮件，被退回来了。

**Comment by yoyooyooo** [comment]
> 视频16m，方便的话，给个其他邮箱。我发给您。刚给你发的邮件，被退回来了。

jihu777@gmail.com

安装按文档一模一样复制到你自己那就行了

**Comment by PayneSnow** [comment]
> 是拖拽多个多个块变成蓝色背景？我一直用没遇到会这样这样，我没装过做过什么修改，能不能录个视频

刚开始正常，使用几个小时后无法选中block了。关闭 qucik 插件，就恢复正常了。下面是视频链接
https://www.notion.so/yu1984/440e0f1e0bf7479c9977bf9aac921b60

**Comment by yoyooyooo** [comment]
> > 是拖拽多个多个块变成蓝色背景？我一直用没遇到会这样这样，我没装过做过什么修改，能不能录个视频
> 
> 刚开始正常，使用几个小时后无法选中block了。关闭 qucik 插件，就恢复正常了。下面是视频链接
> https://www.notion.so/yu1984/440e0f1e0bf7479c9977bf9aac921b60

没权限看不了，，我觉得吧，，几小时后才有问题，很难确定是我的问题，你是精确控制变量法认为是我的问题么，我这边也装了 styled roam 一直没出现你说的问题，顺便问下你装了![dbbBUm](https://cdn.jsdelivr.net/gh/yoyooyooo/file@main/uPic/2021/04/03/dbbBUm.png)  最后边这个图标的『阅读模式』插件没，styled roam 有对他设置快捷键，会不会是你触发了
